training_configuration:
  random_seed: 42
  in_channels: 1
  out_channels: 1
  img_size: [512, 512]
  features: [16, 32, 32, 32, 32]
  decoder_features: [16, 16, 16, 16, 16]
  intermediate: [512, 1024]
  batch_size: 8
  max_epochs: 200
  learning_rate: 0.0001
  num_workers: 0

store_model_to: FOLDER_PATH
